// 03_MOLECULE_Templates/WEB/Web_Component_Library/react/Alert.jsx
import React from "react";
import "../../tokens/components.css";

const ICONS = { info: "i", success: "\u2713", warning: "!", danger: "\u2715" };

/**
 * Alert — inline status callout.
 * <Alert tone="warning" title="Review required">
 *   This change affects production data.
 * </Alert>
 */
export default function Alert({ tone = "info", title, className = "", children, ...rest }) {
  return (
    <div className={`ar-alert ar-alert--${tone} ${className}`.trim()} role="status" {...rest}>
      <span className="ar-alert__icon" aria-hidden="true">{ICONS[tone]}</span>
      <div>
        {title && <p className="ar-alert__title">{title}</p>}
        <p className="ar-alert__body">{children}</p>
      </div>
    </div>
  );
}

// 03_MOLECULE_Templates/WEB/Web_Component_Library/vue/Alert.vue
<template>
  <div class="ar-alert" :class="`ar-alert--${tone}`" role="status">
    <span class="ar-alert__icon" aria-hidden="true">{{ icon }}</span>
    <div>
      <p v-if="title" class="ar-alert__title">{{ title }}</p>
      <p class="ar-alert__body"><slot /></p>
    </div>
  </div>
</template>

<script setup>
import { computed } from "vue";

// Alert — inline status callout.
// <Alert tone="warning" title="Review required">This affects production data.</Alert>
const props = defineProps({
  tone: { type: String, default: "info" }, // info | success | warning | danger
  title: { type: String, default: "" },
});

const ICONS = { info: "i", success: "\u2713", warning: "!", danger: "\u2715" };
const icon = computed(() => ICONS[props.tone]);
</script>

<style>
@import "../../tokens/components.css";
</style>
