// 03_MOLECULE_Templates/WEB/Component_Library/react/Card.jsx
import React from "react";
import "../../tokens/components.css";

/**
 * Card — content container with optional eyebrow/title, or fully custom children.
 *
 * <Card eyebrow="Case Study" title="40% faster claims triage">
 *   Body copy goes here.
 * </Card>
 *
 * <Card interactive onClick={...}><CustomLayout /></Card>
 */
export default function Card({
  eyebrow,
  title,
  interactive = false,
  className = "",
  children,
  ...rest
}) {
  return (
    <div
      className={`ar-card${interactive ? " ar-card--interactive" : ""} ${className}`.trim()}
      role={interactive ? "button" : undefined}
      tabIndex={interactive ? 0 : undefined}
      {...rest}
    >
      {eyebrow && <p className="ar-card__eyebrow">{eyebrow}</p>}
      {title && <h3 className="ar-card__title">{title}</h3>}
      {typeof children === "string" ? <p className="ar-card__body">{children}</p> : children}
    </div>
  );
}

// 03_MOLECULE_Templates/WEB/vue/Card.vue
<template>
  <div
    class="ar-card"
    :class="{ 'ar-card--interactive': interactive }"
    :role="interactive ? 'button' : undefined"
    :tabindex="interactive ? 0 : undefined"
  >
    <p v-if="eyebrow" class="ar-card__eyebrow">{{ eyebrow }}</p>
    <h3 v-if="title" class="ar-card__title">{{ title }}</h3>
    <p v-if="$slots.default && typeof $slots.default()[0]?.children === 'string'" class="ar-card__body">
      <slot />
    </p>
    <slot v-else />
  </div>
</template>

<script setup>
// Card — content container with optional eyebrow/title, or fully custom slot content.
// <Card eyebrow="Case Study" title="40% faster claims triage">Body copy.</Card>
defineProps({
  eyebrow: { type: String, default: "" },
  title: { type: String, default: "" },
  interactive: { type: Boolean, default: false },
});
</script>

<style>
@import "../../tokens/components.css";
</style>
