// 03_MOLECULE_Templates/WEB/vue/Button.vue
<template>
  <component
    :is="as"
    class="ar-btn"
    :class="[`ar-btn--${variant}`, size !== 'md' ? `ar-btn--${size}` : '']"
    :disabled="as === 'button' ? disabled : undefined"
    :aria-disabled="as !== 'button' ? disabled : undefined"
  >
    <slot />
  </component>
</template>

<script setup>
// Button — primary / secondary / ghost variants, 3 sizes.
// <Button variant="primary" @click="...">Get started</Button>
// <Button variant="ghost" size="sm" disabled>Not now</Button>
defineProps({
  variant: { type: String, default: "primary" }, // primary | secondary | ghost
  size: { type: String, default: "md" },          // sm | md | lg
  disabled: { type: Boolean, default: false },
  as: { type: String, default: "button" },
});
</script>

<style>
@import "../../tokens/components.css";
</style>

// 03_MOLECULE_Templates/WEB/react/Button.jsx
import React from "react";
import "../../tokens/components.css";

/**
 * Button — primary / secondary / ghost variants, 3 sizes.
 *
 * <Button variant="primary" onClick={...}>Get started</Button>
 * <Button variant="ghost" size="sm" disabled>Not now</Button>
 */
export default function Button({
  variant = "primary",   // "primary" | "secondary" | "ghost"
  size = "md",            // "sm" | "md" | "lg"
  disabled = false,
  as: Component = "button",
  className = "",
  children,
  ...rest
}) {
  const sizeClass = size !== "md" ? ` ar-btn--${size}` : "";
  return (
    <Component
      className={`ar-btn ar-btn--${variant}${sizeClass} ${className}`.trim()}
      disabled={Component === "button" ? disabled : undefined}
      aria-disabled={Component !== "button" ? disabled : undefined}
      {...rest}
    >
      {children}
    </Component>
  );
}
