// 03_MOLECULE_Templates/WEB/Web_Component_Library/vue/Badge.vue
<template>
  <span class="ar-badge" :class="`ar-badge--${tone}`">
    <slot />
  </span>
</template>

<script setup>
// Badge — small status/category label.
// <Badge tone="success">Live</Badge>
defineProps({
  tone: { type: String, default: "neutral" }, // neutral | brand | info | success | warning | danger
});
</script>

<style>
@import "../../tokens/components.css";
</style>

// 03_MOLECULE_Templates/WEB/Web_Component_Library/react/Badge.jsx
import React from "react";
import "../../tokens/components.css";

/**
 * Badge — small status/category label.
 * <Badge tone="success">Live</Badge>
 */
export default function Badge({ tone = "neutral", className = "", children, ...rest }) {
  return (
    <span className={`ar-badge ar-badge--${tone} ${className}`.trim()} {...rest}>
      {children}
    </span>
  );
}
